### PR TITLE
add rib filtering options to riscli

### PR DESCRIPTION
**Pull request by tobikris**
This implements the #309 feature in the riscli tool.

### CODE REVIEW

**Comment by tobikris** [comment]
I'm not sure why the linter fails, but it seems to be before it looks at the code.
Is it possible that the actions workflow does not work branches from other repos?

**Comment by taktv6** [comment]
Can @corny or @hikhvar say something about that?

**Comment by taktv6** [comment]
LGTM

**Review by taktv6 — DISMISSED** [review]

**Comment by hikhvar** [comment]
I think @awlx can maybe say something about the linter. I don't like that github "magic pile of linter stack" since I don't know how to debug it :-D

**Comment by awlx** [comment]
@hikhvar I never used this linter myself as I find it scary to have "one linter gets it all" I normally add individual linters ... so it's easier to debug.

**Comment by taktv6** [comment]
Would someone mind to file a PR and drop that linter?

**Comment by awlx** [comment]
@tobikris please sync your branch with `master` so we can merge it. Also, maybe that reveals the problem with the linter ... and I am going to fix that.

**Review by awlx — APPROVED** [review]

**Pull request merged**
