### PR TITLE
Use native error wrapping from Go 1.13

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by corny** [comment]
Is there anyone who would like to review my changes?

**Review by mraerino — APPROVED** [review]
wow, this must have been a ton of work, unless you automated it.

changes look good to me.

**Comment by taktv6** [comment]
Thanks for cleaning this up. Much appreaciated!

**Comment by corny** [comment]
It was just two simple replacements with regular expressions in VS code.

**Pull request merged**
