### PR TITLE
Port to google.golang.org/protobuf and buf

### PR DESCRIPTION
**Pull request by leoluk**
This makes it easier for contributors to use the proto workflow.

- Move away from deprecated github.com/golang/protobuf package.
- Use pinned versions of buf, protoc-gen-go and protoc-gen-go-grpc.
- Use relative proto imports.
- Regenerate all protos with the new versions.

### CODE REVIEW

**Comment by awlx** [comment]
Really, cool 🚀. Thank you!

**Comment by awlx** [comment]
Can confirm it works now:
```
python3 -m grpc_tools.protoc -I . -I route/api/ -I net/api --python_betterproto_out=lib cmd/ris/api/ris.proto 
Writing __init__.py
Writing bio/__init__.py
Writing bio/net.py
Writing bio/ris.py
Writing bio/route.py
```

**Review by awlx — DISMISSED** [review]

**Comment by taktv6** [comment]
LGTM. Not sure why the build is not triggered.

**Comment by leoluk** [comment]
The test failure is present on master:

```
$ git log -n 1 
commit c6d38ad4a676f961e1025199336da777ba7a74da (HEAD, origin/master, origin/HEAD, leoluk/master, master)
Author: Tobias Krischer <tobikris@users.noreply.github.com>
Date:   Mon Nov 29 13:44:26 2021 +0100

    add rib filtering (#309)
    
    * add rib filtering
    
    * add simple test for route.IsBGPOriginatedBy
    
    * add test names
$ CGO_ENABLED=0 go test -v github.com/bio-routing/bio-rd/protocols/bgp/server
=== RUN   TestDumpRIBInOut
--- PASS: TestDumpRIBInOut (0.00s)
=== RUN   TestBMPServer
time="2021-11-30T18:15:17Z" level=info msg="Received initiation message from 10.0.255.1: sysDescr.: BBBB sysName.: AAAA"
time="2021-11-30T18:15:17Z" level=info msg="peer up notification received" address=10.0.255.1 peer_address=10.1.1.1 peer_distinguisher="0:123" router=AAAA
time="2021-11-30T18:15:17Z" level=info msg="peer up notification received" address=10.0.255.1 peer_address=10.1.2.1 peer_distinguisher="0:123" router=AAAA
time="2021-11-30T18:15:17Z" level=info msg="peer up notification received" address=10.0.255.1 peer_address=10.1.2.1 peer_distinguisher="0:0" router=AAAA
time="2021-11-30T18:15:17Z" level=info msg="peer down notification received" address=10.0.255.1 peer_address=10.1.2.1 peer_distinguisher="0:0" router=AAAA
time="2021-11-30T18:15:17Z" level=info msg="peer down notification received" address=10.0.255.1 peer_address=10.1.1.1 peer_distinguisher="0:123" router=AAAA
time="2021-11-30T18:15:17Z" level=warning msg="Received termination message from 10.0.255.1: Session administratively down"
--- PASS: TestBMPServer (0.00s)
=== RUN   TestFSMAFIInitDispose
    fsm_address_family_test.go:53: 
        	Error Trace:	fsm_address_family_test.go:53
        	Error:      	Not equal: 
        	           	expected: &sync.WaitGroup{noCopy:sync.noCopy{}, state1:[3]uint32{0x0, 0x0, 0x1}}
        	           	actual  : &sync.WaitGroup{noCopy:sync.noCopy{}, state1:[3]uint32{0x0, 0x1, 0x0}}
        	           	
        	           	Diff:
        	           	--- Expected
        	           	+++ Actual
        	           	@@ -5,4 +5,4 @@
        	           	  (uint32) 0,
        	           	-  (uint32) 0,
        	           	-  (uint32) 1
        	           	+  (uint32) 1,
        	           	+  (uint32) 0
        	           	 }
        	Test:       	TestFSMAFIInitDispose
```

**Review by awlx — APPROVED** [review]
Tested it in my lab and it seems fine.

**Pull request merged**
